### PR TITLE
Change defaults for checking vectors/linearity/symmetry in check_ functions

### LINKED ISSUE #245: check_gradient always fails
Is `check_gradient` working properly? I don't seem to have it return true, even on simple functions.

Even taking the sample `f` and `grad_f` from the [docs](https://manoptjl.org/stable/tutorials/Optimize!/) fails:
```julia
using Manopt, Manifolds, Random, LinearAlgebra
Random.seed!(42);
n = 100
σ = π / 8
M = Sphere(2)
p = 1 / sqrt(2) * [1.0, 0.0, 1.0]
data = [exp(M, p,  σ * rand(M; vector_at=p)) for i in 1:n];
f(M, p) = sum(1 / (2 * n) * distance.(Ref(M), Ref(p), data) .^ 2)
grad_f(M, p) = sum(1 / n * grad_distance.(Ref(M), data, Ref(p)));
check_gradient(M, f, grad_f, throw_error=true)
```
returns
```julia
ERROR: DomainError with 2.687604283142213e-16:
The vector [-1.001187263626093, 0.1028991640105687, -0.887807346557081] is not a tangent vector to [-0.42344094610973243, 0.7120699114881195, 0.5600483964007007] on Sphere(2, ℝ), since it is not orthogonal in the embedding.
Stacktrace:
 [1] is_vector(::ManifoldsBase.TraitList{IsEmbeddedManifold, ManifoldsBase.TraitList{IsDefaultMetric{EuclideanMetric}, ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.EmptyTrait}}}, M::Sphere{2, ℝ}, p::Vector{Float64}, X::Vector{Float64}, te::Bool, cbp::Bool; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/ROusQ/src/decorator_trait.jl:481
 [2] is_vector
   @ ~/.julia/packages/ManifoldsBase/ROusQ/src/decorator_trait.jl:435 [inlined]
 [3] is_vector(_t::ManifoldsBase.TraitList{IsIsometricEmbeddedManifold, ManifoldsBase.TraitList{IsEmbeddedManifold, ManifoldsBase.TraitList{IsDefaultMetric{EuclideanMetric}, ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.EmptyTrait}}}}, M::Sphere{2, ℝ}, p::Vector{Float64}, X::Vector{Float64}, te::Bool, cbp::Bool; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/ROusQ/src/nested_trait.jl:313
 [4] is_vector(_t::ManifoldsBase.TraitList{IsIsometricEmbeddedManifold, ManifoldsBase.TraitList{IsEmbeddedManifold, ManifoldsBase.TraitList{IsDefaultMetric{EuclideanMetric}, ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.EmptyTrait}}}}, M::Sphere{2, ℝ}, p::Vector{Float64}, X::Vector{Float64}, te::Bool, cbp::Bool)
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/ROusQ/src/nested_trait.jl:308
 [5] is_vector(M::Sphere{2, ℝ}, p::Vector{Float64}, X::Vector{Float64}, te::Bool, cbp::Bool; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ManifoldsBase ~/.julia/packages/ManifoldsBase/ROusQ/src/nested_trait.jl:306
 [6] is_vector (repeats 2 times)
   @ ~/.julia/packages/ManifoldsBase/ROusQ/src/nested_trait.jl:305 [inlined]
 [7] check_gradient(M::Sphere{2, ℝ}, f::Function, grad_f::Function, p::Vector{Float64}, X::Vector{Float64}; gradient::Vector{Float64}, check_vector::Bool, throw_error::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Manopt ~/.julia/packages/Manopt/Wl0jp/src/helpers/checks.jl:187
 [8] top-level scope
   @ REPL[37]:1
```
Apparently the problem is that `2.687604283142213e-16` is not exactly zero?

### PR DESCRIPTION
**Pull request by kellertuer**
This introduces `atol` and `rtol` to both the gradient and the Hessian check. These are passed down tp the `is_vector` check and for the Hessian also to the Linearity and symmetry check, in other words all places that call `is_approx`.  

This resolves #245.

### CODE REVIEW

File: src/helpers/checks.jl [hunk 1]
```diff
@@ -180,11 +184,14 @@ function check_gradient(
     p=rand(M),
     X=rand(M; vector_at=p);
     gradient=grad_f(M, p),
-    check_vector=true,
+    check_vector=false,
     throw_error=false,
+    atol::Real=0,
```
Comment (mateuszbaran) [inline src/helpers/checks.jl:189]: Maybe `atol` for tangent vector checks shouldn't be 0 by default because very often such checks compare with 0, and `atol` equal to 0 turns such checks into exact equality.

Comment (kellertuer) [reply src/helpers/checks.jl:189]: For best of cases I would just want to pass down kwargs to the check and have proper defaults in Manifolds...
until then – should we really introduce a new default here in this niche of the ecosystem?

Comment (mateuszbaran) [reply src/helpers/checks.jl:189]: OK, we can leave that for later.
